### PR TITLE
Add composite keyword with go definition which spilt by AND

### PR DESCRIPTION
**Pull request by WindAzure**
example =>  Suite Setup    Run Keywords    Open Browser    AND    Say Hello
Support **Open Browser**, **Say Hello** could also go definition

### CODE REVIEW

**Comment by tomi** [comment]
Hi and thank you for your PR! I apologize for not checking it earlier, but I'll try to go through it in the near future.

**Comment by WindAzure** [comment]
Hello there,
No problem! I'm very glad to contribute this wonder extension!
I made some enhancement After Mar 31 and made PR just now.
Would you please check for it?

1.  Support GO TO DEFINITION in [Setup]/[Teardown] block
2.  Keywords which without AND concated could also support GO TO DEFINITION.

**Comment by tomi** [comment]
I took a look at the PR. I think there are couple of issues with how this is currently implemented.

1. We lose information. The keywords `Run Keywords` and `Run Keyword And Ignore Error` themselves are discarded and only the keywords they call are stored. If we ever want to add "Go to definition" support for library keywords like `Run Keywords`, it wouldn't be possible.
1. The implementation is not universal. With this I mean that this works now with `Suite Setting`, `Setup` and `Teardown`, but nothing prevents you from using a keyword like `Run Keywords` in a test case or keyword definition. This would need a separate implementation.

I would suggest a different way to implement this, which would fix the above mentioned issues:

- Change the `CallExpression` model's `args` member from `args: ValueExpression[]` to `args: Expression[]`. This allows `CallExpression` to be an argument for another `CallExpression`
- Change `parseCallExpression` to handle special keywords like `Run Keywords`, and `Run Keyword And Ignore Error` that accept other keywords as arguments. These should be parsed as `CallExpression`s in the arguments of the "main" `CallExpression`.

As an example,

```robot
Suite Setup    Run Keywords    Open Default Browser    AND    Say Hello
```

would be parsed as:

```ts
new SuiteSetting(
  new Identifier("Suite Setup"),
  new CallExpression(
    new Identifier("Run Keywords"),
    [
      new CallExpression(
        new Identifier("Open Default Browser")
      ),
      new Literal("AND"),
      new CallExpression(
        new Identifier("Say Hello")
      ),
    ]
  )
)
```

After this everything should work out of the box.

**Comment by WindAzure** [comment]
It seems wired if library keywords was made with ```Run Keywords``` ( Example ), so maybe we don't have to consider this case before made solutions to solve it.

Example,
```
MyTestCases1.txt
Hover Button Should Show tooltips
    Delete Device Button

KeywordLibrary1.txt
Eat Meat
    Go Eat Meat

Drink Water
    Go Drink Water

Delete Device Button
    Run Keywords    Eat Meat    AND    Drink Water
```

I agree using ```Run Keywords/Run Keyword And Ignore Error``` to put keywords together in ```[setup]/[teardown]``` was not good idea, but it could be a feature that could have.
We have same idea to treat special keywords, but I choose ignore it rather save as ```Literal```.
There's a [Composite Parser](https://github.com/WindAzure/vscode-rf-language-server/blob/master/server/src/parser/composite-keywords-parser.ts) to manage parsing logic. It will filter all special keywords in blacklist to guaranty not show it in ```CallExpression```.

**Comment by WindAzure** [comment]
@tomi  If you have any questions or concerns about my PR, please feel free to let me know, thanks!

**Comment by tomi** [comment]
Like I mentioned in my earlier comment, the way this has been implemented now has issues. Even tho the parser is part of this extension, it should be thought of as an independent component, like `esprima` for example. This PR would make the parser lose information about the code it parses, which I can not accept. It would be the same if a JS parser would ignore some function and just take it's parameters.

Also, if this was implemented like I described above, it would give us the foundation to handle keywords that accept keywords as parameters everywhere.

So, I'm sorry but I won't merge this before the changes mentioned above are made.

**Comment by tomi** [comment]
I'm closing this as this functionality was implemented in PR #36

**Pull request closed without merging**
